src/abis/CollectionFactory.ts
src/abis/Forwarder.ts
src/abis/index.ts
src/contracts/collectionFactory.ts
src/contracts/collectionManager.ts
src/contracts/collectionStore.ts
src/contracts/committee.ts
src/contracts/erc721CollectionV2.ts
src/contracts/forwarder.ts
src/contracts/index.ts
src/contracts/manaToken.ts
src/contracts/marketplace.ts
src/contracts/rarities.ts
src/types.ts

- CollectionFactory
- Forwarder

feat: add new collections

---

src/sendMetaTransaction.ts
src/utils.ts

feat: support Fortmatic and wallets without eth_requestAccounts

---

src/utils.ts
test/utils.spec.ts

fix: meta txs with ledger

---

src/contracts/erc20.ts
src/contracts/erc721.ts

Added missing chains to erc20 and erc721

fix: added missing chains to erc20 and erc721

---

src/abis/ThirdPartyRegistry.ts
src/abis/Tiers.ts
src/abis/index.ts
src/contracts/index.ts
src/contracts/thirdPartyRegistry.ts
src/contracts/tiers.ts
src/types.ts

This PR adds the tiers and third party registry contracts so they can be used in the dApps.\
The ABIs can be found in the [tpr-graph repository](https://github.com/decentraland/tpr-graph/tree/master/abis) and the [mumbai addresses too](https://github.com/decentraland/tpr-graph/blob/master/config/mumbai.json).

feat: Add the tiers and third party registry contracts

---

src/abis/ThirdPartyRegistry.ts
src/contracts/thirdPartyRegistry.ts

Changed address and ABI for TPR contract

chore: New TPR version

---

package-lock.json
package.json
src/errors.ts
src/sendMetaTransaction.ts
test/errors.spec.ts

feat: sale price too low error

---

src/contracts/collectionFactoryV3.ts

Add matic mainnet factory v3 contract to lib

feat: Factory V3 Mainnet

---

src/abis/Rentals.ts
src/contracts/rentals.ts

feat: Update rentals abi and address for goerli

---

src/sendMetaTransaction.ts

This PR updates body error priority over response error

fix: Update body error priority over response error

---

src/abis/DCLController.ts
src/abis/DCLControllerV2.ts
src/abis/DCLRegistrar.ts
src/abis/index.ts
src/contracts/dclController.ts
src/contracts/dclControllerV2.ts
src/contracts/dclRegistrar.ts
src/contracts/index.ts
src/types.ts

Closes #63 
Adds DCLController, DCLControllerV2 and DCLRegistrar contracts to both Mainnet and Goerli chains

feat: Add registrar and controller contracts

---

src/crossChain/AxelarProvider.ts
src/crossChain/types.ts

This PR adds the Axelar route to the Axelar Provider.

feat: Add cross chain name minting

---

src/crossChain/types.ts

This PR adds the new method to the interface.

fix: Add get register name route to interface

---

src/contracts/bidV2.ts
src/contracts/chainlinkOracle.ts
src/contracts/collectionFactoryV3.ts
src/contracts/collectionManager.ts
src/contracts/collectionStore.ts
src/contracts/committee.ts
src/contracts/erc721CollectionV2.ts
src/contracts/forwarder.ts
src/contracts/manaToken.ts
src/contracts/marketplaceV2.ts
src/contracts/rarities.ts
src/contracts/raritiesWithOracle.ts

This PR adds the polygon amoy contracts

feat: Add polygon amoy contracts

---

package-lock.json
package.json
src/abis/OffChainMarketplace.ts
src/abis/index.ts
src/contracts/index.ts
src/contracts/offChainMarketplace.ts
src/types.ts

Add new offchain marketplace contract

feat: add new offchain marketplace

---

src/contracts/offChainMarketplace.ts

Add offchain marketrplace amoy connfiguration and change contract name and version

feat: add offchain marketplace in amoy

---

src/abis/OffChainMarketplaceEthereum.ts
src/abis/OffChainMarketplacePolygon.ts
src/abis/index.ts
src/contracts/offChainMarketplace.ts

Update addresses for off chain marketplace contract
Add both abis for polygon and ethereum as they are slightly different

feat: update offchain marketplace contract addresses

---

package-lock.json
src/contracts/offChainMarketplace.ts

Add mainnet contracts for offchain marketplace

feat: add mainnet contracts for offchain marketplace

---

src/abis/ThirdPartyRegistry.ts
src/contracts/thirdPartyRegistry.ts

This PR adds the new third party registry ABI and contract address for the Amoy network.

feat: Third Party Upgrade

---

src/crossChain/AxelarProvider.ts

This PR fixes the calldata used for the `accept` contract call on the Axellar calls.

fix: Accept trade calldata

---

README.md
package.json
scripts/convertAbiToJson.ts
scripts/extractFunctionDataForTenderly.ts
scripts/extractFunctionDataWithABI.ts
scripts/utils.ts

This PR adds three new scripts to debug meta transactions.

feat: Add transaction debugging scripts
